# Generated by Django 4.0.5 on 2022-11-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='multiple_option',
            field=models.BooleanField(blank=True, max_length=2000, null=True),
        ),
    ]
